name=mongo-sink-from-mysql
connector.class=com.mongodb.kafka.connect.MongoSinkConnector
tasks.max=1
topics=mysql-server.kafkadb.categories
connection.uri=mongodb://${MONGO_ROOT_USERNAME}:${MONGO_ROOT_PASSWORD}@mongodb/
database=kafkadb
transforms=extractAddress
transforms.extractAddress.type=org.apache.kafka.connect.transforms.ExtractField$Value
transforms.extractAddress.field=after