name=mysql-connector
connector.class=io.debezium.connector.mysql.MySqlConnector
tasks.max=1
database.hostname=mysql
database.port=3306
database.server.name=mysql-server
# Use a dedicated user with minimum privileges: SELECT, RELOAD, SHOW DATABASES, REPLICATION SLAVE, REPLICATION CLIENT
database.user=${MYSQL_CDC_USER}
database.password=${MYSQL_CDC_PASSWORD}
database.include.list=kafkadb
table.include.list=kafkadb.categories,kafkadb.products,kafkadb.orders,kafkadb.order_items
database.history.kafka.bootstrap.servers=kafka:9092
database.history.kafka.topic=mysql_history